ALTER TABLE K12INTEL_DW.DTBL_STUDENTS
MODIFY (STUDENT_ESL_INDICATOR VARCHAR2(10));

ALTER TABLE K12INTEL_DW.DTBL_STUDENT_ANNUAL_ATTRIBS
MODIFY (STUDENT_ESL_INDICATOR VARCHAR2(10));

ALTER TABLE K12INTEL_DW.DTBL_STUDENTS_EVOLVED
MODIFY (STUDENT_ESL_INDICATOR VARCHAR2(10));

ALTER TABLE K12INTEL_DW.DTBL_STUDENT_ATTRIBS
MODIFY (STUDENT_ESL_INDICATOR VARCHAR2(10));

ALTER TABLE K12INTEL_REPORTING.MTBL_STUDENT_SUMMARY
MODIFY (STUDENT_ESL_INDICATOR VARCHAR2(10));

COMMIT;