--Counts on tables
SELECT SCHOOL_YEAR, STUDENT_ESL_CLASSIFICATION, STUDENT_ESL_INDICATOR, COUNT(*) 
FROM K12INTEL_DW.DTBL_STUDENT_ANNUAL_ATTRIBS
WHERE 1=1
AND STUDENT_ESL_CLASSIFICATION = '6'
GROUP BY
    STUDENT_ESL_CLASSIFICATION, STUDENT_ESL_INDICATOR, SCHOOL_YEAR
ORDER BY 1
;
SELECT STUDENT_ESL_CLASSIFICATION, STUDENT_ESL_INDICATOR, COUNT(*) 
FROM K12INTEL_DW.DTBL_STUDENT_ATTRIBS
WHERE 1=1
AND STUDENT_ESL_CLASSIFICATION = '6'
GROUP BY
    STUDENT_ESL_CLASSIFICATION, STUDENT_ESL_INDICATOR
ORDER BY 1
;
SELECT STUDENT_ESL_CLASSIFICATION, STUDENT_ESL_INDICATOR, COUNT(*) 
FROM K12INTEL_DW.DTBL_STUDENTS_EVOLVED
WHERE 1=1
AND STUDENT_ESL_CLASSIFICATION = '6'
GROUP BY
    STUDENT_ESL_CLASSIFICATION, STUDENT_ESL_INDICATOR
ORDER BY 1
;
--Update Student Annual Attribs (57276 rows in first)
SELECT * FROM K12INTEL_DW.DTBL_STUDENT_ANNUAL_ATTRIBS
WHERE STUDENT_ESL_INDICATOR = 'No' and STUDENT_ESL_CLASSIFICATION = '6'
--WHERE STUDENT_ESL_INDICATOR = 'Former'
;
UPDATE K12INTEL_DW.DTBL_STUDENT_ANNUAL_ATTRIBS
SET STUDENT_ESL_INDICATOR = 'Former', SYS_UPDATED = SYSDATE
WHERE STUDENT_ESL_INDICATOR = 'No' and STUDENT_ESL_CLASSIFICATION = '6'
;
--Update Students Evolved (295629 rows in first)
SELECT * FROM K12INTEL_DW.DTBL_STUDENTS_EVOLVED
WHERE STUDENT_ESL_INDICATOR = 'No' and STUDENT_ESL_CLASSIFICATION = '6'
--WHERE STUDENT_ESL_INDICATOR = 'Former'
;
UPDATE K12INTEL_DW.DTBL_STUDENTS_EVOLVED
SET STUDENT_ESL_INDICATOR = 'Former', SYS_UPDATED = SYSDATE
WHERE STUDENT_ESL_INDICATOR = 'No' and STUDENT_ESL_CLASSIFICATION = '6'
;
COMMIT;